import 'package:dio/dio.dart';

///temporary will be removed after auth works
class TempAuthInterceptor extends Interceptor {
  static const String tempToken =
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YjI0ZWE4My1iMjE1LTQyYTktYTFmMC1iMmI4ODExN2FhNWMiLCJqdGkiOiIxOWE3ZTdlZC0wMzc3LTRhZTEtYWJmMC1hMzllMjhhMDZlOGMiLCJlbWFpbCI6ImF5YTEyNzk5N0BnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6ImF5YTEyNzk5N0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjZiMjRlYTgzLWIyMTUtNDJhOS1hMWYwLWIyYjg4MTE3YWE1YyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJheWEiLCJVc2VyVHlwZSI6Ik93bmVyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiT3duZXIiLCJleHAiOjE3ODg4MDE3MTgsImlzcyI6IldhdGFkQXBpIiwiYXVkIjoiV2F0YWRVc2VycyJ9.mVXQSW2ZAdPQ0XbEVir7VM6qFT_XDHYblQgqAWGhWJk";
  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    options.headers['Authorization'] = 'Bearer $tempToken';
    handler.next(options);
  }
}